// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AnimFrameBucket.proto
// Protobuf C++ Version: 6.32.0-dev

#include "AnimFrameBucket.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr AnimFrameBucket_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pobone_{},
        keyframe_{0u},
        numnodes_{0u},
        keytime_{0},
        keytimeindex_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AnimFrameBucket_proto::AnimFrameBucket_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(AnimFrameBucket_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AnimFrameBucket_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnimFrameBucket_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnimFrameBucket_protoDefaultTypeInternal() {}
  union {
    AnimFrameBucket_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnimFrameBucket_protoDefaultTypeInternal _AnimFrameBucket_proto_default_instance_;
// ===================================================================

class AnimFrameBucket_proto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AnimFrameBucket_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_._has_bits_);
};

void AnimFrameBucket_proto::clear_pobone() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pobone_.Clear();
}
AnimFrameBucket_proto::AnimFrameBucket_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, AnimFrameBucket_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AnimFrameBucket_proto)
}
PROTOBUF_NDEBUG_INLINE AnimFrameBucket_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::AnimFrameBucket_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pobone_{visibility, arena, from.pobone_} {}

AnimFrameBucket_proto::AnimFrameBucket_proto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AnimFrameBucket_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, AnimFrameBucket_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AnimFrameBucket_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, keyframe_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, keyframe_),
           offsetof(Impl_, keytimeindex_) -
               offsetof(Impl_, keyframe_) +
               sizeof(Impl_::keytimeindex_));

  // @@protoc_insertion_point(copy_constructor:AnimFrameBucket_proto)
}
PROTOBUF_NDEBUG_INLINE AnimFrameBucket_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        pobone_{visibility, arena} {}

inline void AnimFrameBucket_proto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, keyframe_),
           0,
           offsetof(Impl_, keytimeindex_) -
               offsetof(Impl_, keyframe_) +
               sizeof(Impl_::keytimeindex_));
}
AnimFrameBucket_proto::~AnimFrameBucket_proto() {
  // @@protoc_insertion_point(destructor:AnimFrameBucket_proto)
  SharedDtor(*this);
}
inline void AnimFrameBucket_proto::SharedDtor(MessageLite& self) {
  AnimFrameBucket_proto& this_ = static_cast<AnimFrameBucket_proto&>(self);
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AnimFrameBucket_proto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AnimFrameBucket_proto(arena);
}
constexpr auto AnimFrameBucket_proto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_.pobone_) +
          decltype(AnimFrameBucket_proto::_impl_.pobone_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(AnimFrameBucket_proto), alignof(AnimFrameBucket_proto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&AnimFrameBucket_proto::PlacementNew_,
                                 sizeof(AnimFrameBucket_proto),
                                 alignof(AnimFrameBucket_proto));
  }
}
constexpr auto AnimFrameBucket_proto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<22>{
      {
          &_AnimFrameBucket_proto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &AnimFrameBucket_proto::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<AnimFrameBucket_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AnimFrameBucket_proto::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<AnimFrameBucket_proto>(), &AnimFrameBucket_proto::ByteSizeLong,
              &AnimFrameBucket_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_._cached_size_),
          true,
      },
      "AnimFrameBucket_proto",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<22> AnimFrameBucket_proto_class_data_ =
    AnimFrameBucket_proto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AnimFrameBucket_proto::GetClassData() const {
  return AnimFrameBucket_proto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 1, 0, 2>
AnimFrameBucket_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    AnimFrameBucket_proto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AnimFrameBucket_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint32 keyFrame = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_.keyframe_)}},
    // optional uint32 numNodes = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_.numnodes_)}},
    // optional float keyTime = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0, PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_.keytime_)}},
    // optional int32 keyTimeIndex = 4;
    {::_pbi::TcParser::FastV32S1,
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_.keytimeindex_)}},
    // repeated .AnimBone_proto poBone = 5;
    {::_pbi::TcParser::FastMtR1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_.pobone_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 keyFrame = 1;
    {PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_.keyframe_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 numNodes = 2;
    {PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_.numnodes_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional float keyTime = 3;
    {PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_.keytime_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional int32 keyTimeIndex = 4;
    {PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_.keytimeindex_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // repeated .AnimBone_proto poBone = 5;
    {PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_.pobone_), -1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::AnimBone_proto>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void AnimFrameBucket_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:AnimFrameBucket_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pobone_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fU) != 0) {
    ::memset(&_impl_.keyframe_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.keytimeindex_) -
        reinterpret_cast<char*>(&_impl_.keyframe_)) + sizeof(_impl_.keytimeindex_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AnimFrameBucket_proto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AnimFrameBucket_proto& this_ = static_cast<const AnimFrameBucket_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AnimFrameBucket_proto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AnimFrameBucket_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AnimFrameBucket_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 keyFrame = 1;
  if ((cached_has_bits & 0x00000001U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_keyframe(), target);
  }

  // optional uint32 numNodes = 2;
  if ((cached_has_bits & 0x00000002U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_numnodes(), target);
  }

  // optional float keyTime = 3;
  if ((cached_has_bits & 0x00000004U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this_._internal_keytime(), target);
  }

  // optional int32 keyTimeIndex = 4;
  if ((cached_has_bits & 0x00000008U) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
            stream, this_._internal_keytimeindex(), target);
  }

  // repeated .AnimBone_proto poBone = 5;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_pobone_size());
       i < n; i++) {
    const auto& repfield = this_._internal_pobone().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            5, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AnimFrameBucket_proto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AnimFrameBucket_proto::ByteSizeLong(const MessageLite& base) {
  const AnimFrameBucket_proto& this_ = static_cast<const AnimFrameBucket_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AnimFrameBucket_proto::ByteSizeLong() const {
  const AnimFrameBucket_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AnimFrameBucket_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .AnimBone_proto poBone = 5;
    {
      total_size += 1UL * this_._internal_pobone_size();
      for (const auto& msg : this_._internal_pobone()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000004U & cached_has_bits) * 5;
  if ((cached_has_bits & 0x0000000bU) != 0) {
    // optional uint32 keyFrame = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_keyframe());
    }
    // optional uint32 numNodes = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_numnodes());
    }
    // optional int32 keyTimeIndex = 4;
    if ((cached_has_bits & 0x00000008U) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_keytimeindex());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void AnimFrameBucket_proto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AnimFrameBucket_proto*>(&to_msg);
  auto& from = static_cast<const AnimFrameBucket_proto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AnimFrameBucket_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_pobone()->MergeFrom(
      from._internal_pobone());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fU) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _this->_impl_.keyframe_ = from._impl_.keyframe_;
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _this->_impl_.numnodes_ = from._impl_.numnodes_;
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      _this->_impl_.keytime_ = from._impl_.keytime_;
    }
    if ((cached_has_bits & 0x00000008U) != 0) {
      _this->_impl_.keytimeindex_ = from._impl_.keytimeindex_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void AnimFrameBucket_proto::CopyFrom(const AnimFrameBucket_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AnimFrameBucket_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AnimFrameBucket_proto::InternalSwap(AnimFrameBucket_proto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pobone_.InternalSwap(&other->_impl_.pobone_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_.keytimeindex_)
      + sizeof(AnimFrameBucket_proto::_impl_.keytimeindex_)
      - PROTOBUF_FIELD_OFFSET(AnimFrameBucket_proto, _impl_.keyframe_)>(
          reinterpret_cast<char*>(&_impl_.keyframe_),
          reinterpret_cast<char*>(&other->_impl_.keyframe_));
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
