// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AnimQuat.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef AnimQuat_2eproto_2epb_2eh
#define AnimQuat_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_AnimQuat_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_AnimQuat_2eproto {
  static const ::uint32_t offsets[];
};
class AnimQuat_proto;
struct AnimQuat_protoDefaultTypeInternal;
extern AnimQuat_protoDefaultTypeInternal _AnimQuat_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<15> AnimQuat_proto_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class AnimQuat_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:AnimQuat_proto) */ {
 public:
  inline AnimQuat_proto() : AnimQuat_proto(nullptr) {}
  ~AnimQuat_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AnimQuat_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AnimQuat_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AnimQuat_proto(::google::protobuf::internal::ConstantInitialized);

  inline AnimQuat_proto(const AnimQuat_proto& from) : AnimQuat_proto(nullptr, from) {}
  inline AnimQuat_proto(AnimQuat_proto&& from) noexcept
      : AnimQuat_proto(nullptr, ::std::move(from)) {}
  inline AnimQuat_proto& operator=(const AnimQuat_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnimQuat_proto& operator=(AnimQuat_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const AnimQuat_proto& default_instance() {
    return *reinterpret_cast<const AnimQuat_proto*>(
        &_AnimQuat_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AnimQuat_proto& a, AnimQuat_proto& b) { a.Swap(&b); }
  inline void Swap(AnimQuat_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnimQuat_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnimQuat_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<AnimQuat_proto>(arena);
  }
  void CopyFrom(const AnimQuat_proto& from);
  void MergeFrom(const AnimQuat_proto& from) { AnimQuat_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AnimQuat_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "AnimQuat_proto"; }

 protected:
  explicit AnimQuat_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AnimQuat_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AnimQuat_proto& from);
  AnimQuat_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AnimQuat_proto&& from) noexcept
      : AnimQuat_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kQxFieldNumber = 1,
    kQyFieldNumber = 2,
    kQzFieldNumber = 3,
    kQwFieldNumber = 4,
  };
  // optional float qx = 1;
  bool has_qx() const;
  void clear_qx() ;
  float qx() const;
  void set_qx(float value);

  private:
  float _internal_qx() const;
  void _internal_set_qx(float value);

  public:
  // optional float qy = 2;
  bool has_qy() const;
  void clear_qy() ;
  float qy() const;
  void set_qy(float value);

  private:
  float _internal_qy() const;
  void _internal_set_qy(float value);

  public:
  // optional float qz = 3;
  bool has_qz() const;
  void clear_qz() ;
  float qz() const;
  void set_qz(float value);

  private:
  float _internal_qz() const;
  void _internal_set_qz(float value);

  public:
  // optional float qw = 4;
  bool has_qw() const;
  void clear_qw() ;
  float qw() const;
  void set_qw(float value);

  private:
  float _internal_qw() const;
  void _internal_set_qw(float value);

  public:
  // @@protoc_insertion_point(class_scope:AnimQuat_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AnimQuat_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    float qx_;
    float qy_;
    float qz_;
    float qw_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AnimQuat_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<15> AnimQuat_proto_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AnimQuat_proto

// optional float qx = 1;
inline bool AnimQuat_proto::has_qx() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void AnimQuat_proto::clear_qx() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qx_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline float AnimQuat_proto::qx() const {
  // @@protoc_insertion_point(field_get:AnimQuat_proto.qx)
  return _internal_qx();
}
inline void AnimQuat_proto::set_qx(float value) {
  _internal_set_qx(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:AnimQuat_proto.qx)
}
inline float AnimQuat_proto::_internal_qx() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qx_;
}
inline void AnimQuat_proto::_internal_set_qx(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qx_ = value;
}

// optional float qy = 2;
inline bool AnimQuat_proto::has_qy() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void AnimQuat_proto::clear_qy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qy_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline float AnimQuat_proto::qy() const {
  // @@protoc_insertion_point(field_get:AnimQuat_proto.qy)
  return _internal_qy();
}
inline void AnimQuat_proto::set_qy(float value) {
  _internal_set_qy(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:AnimQuat_proto.qy)
}
inline float AnimQuat_proto::_internal_qy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qy_;
}
inline void AnimQuat_proto::_internal_set_qy(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qy_ = value;
}

// optional float qz = 3;
inline bool AnimQuat_proto::has_qz() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  return value;
}
inline void AnimQuat_proto::clear_qz() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qz_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline float AnimQuat_proto::qz() const {
  // @@protoc_insertion_point(field_get:AnimQuat_proto.qz)
  return _internal_qz();
}
inline void AnimQuat_proto::set_qz(float value) {
  _internal_set_qz(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:AnimQuat_proto.qz)
}
inline float AnimQuat_proto::_internal_qz() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qz_;
}
inline void AnimQuat_proto::_internal_set_qz(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qz_ = value;
}

// optional float qw = 4;
inline bool AnimQuat_proto::has_qw() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008U) != 0;
  return value;
}
inline void AnimQuat_proto::clear_qw() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qw_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008U;
}
inline float AnimQuat_proto::qw() const {
  // @@protoc_insertion_point(field_get:AnimQuat_proto.qw)
  return _internal_qw();
}
inline void AnimQuat_proto::set_qw(float value) {
  _internal_set_qw(value);
  _impl_._has_bits_[0] |= 0x00000008U;
  // @@protoc_insertion_point(field_set:AnimQuat_proto.qw)
}
inline float AnimQuat_proto::_internal_qw() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.qw_;
}
inline void AnimQuat_proto::_internal_set_qw(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.qw_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // AnimQuat_2eproto_2epb_2eh
