// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AnimFrameBucket.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef AnimFrameBucket_2eproto_2epb_2eh
#define AnimFrameBucket_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "AnimBone.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_AnimFrameBucket_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_AnimFrameBucket_2eproto {
  static const ::uint32_t offsets[];
};
class AnimFrameBucket_proto;
struct AnimFrameBucket_protoDefaultTypeInternal;
extern AnimFrameBucket_protoDefaultTypeInternal _AnimFrameBucket_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<22> AnimFrameBucket_proto_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class AnimFrameBucket_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:AnimFrameBucket_proto) */ {
 public:
  inline AnimFrameBucket_proto() : AnimFrameBucket_proto(nullptr) {}
  ~AnimFrameBucket_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AnimFrameBucket_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AnimFrameBucket_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AnimFrameBucket_proto(::google::protobuf::internal::ConstantInitialized);

  inline AnimFrameBucket_proto(const AnimFrameBucket_proto& from) : AnimFrameBucket_proto(nullptr, from) {}
  inline AnimFrameBucket_proto(AnimFrameBucket_proto&& from) noexcept
      : AnimFrameBucket_proto(nullptr, ::std::move(from)) {}
  inline AnimFrameBucket_proto& operator=(const AnimFrameBucket_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnimFrameBucket_proto& operator=(AnimFrameBucket_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const AnimFrameBucket_proto& default_instance() {
    return *reinterpret_cast<const AnimFrameBucket_proto*>(
        &_AnimFrameBucket_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AnimFrameBucket_proto& a, AnimFrameBucket_proto& b) { a.Swap(&b); }
  inline void Swap(AnimFrameBucket_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnimFrameBucket_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnimFrameBucket_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<AnimFrameBucket_proto>(arena);
  }
  void CopyFrom(const AnimFrameBucket_proto& from);
  void MergeFrom(const AnimFrameBucket_proto& from) { AnimFrameBucket_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AnimFrameBucket_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "AnimFrameBucket_proto"; }

 protected:
  explicit AnimFrameBucket_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AnimFrameBucket_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AnimFrameBucket_proto& from);
  AnimFrameBucket_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AnimFrameBucket_proto&& from) noexcept
      : AnimFrameBucket_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPoBoneFieldNumber = 5,
    kKeyFrameFieldNumber = 1,
    kNumNodesFieldNumber = 2,
    kKeyTimeFieldNumber = 3,
    kKeyTimeIndexFieldNumber = 4,
  };
  // repeated .AnimBone_proto poBone = 5;
  int pobone_size() const;
  private:
  int _internal_pobone_size() const;

  public:
  void clear_pobone() ;
  ::AnimBone_proto* PROTOBUF_NONNULL mutable_pobone(int index);
  ::google::protobuf::RepeatedPtrField<::AnimBone_proto>* PROTOBUF_NONNULL mutable_pobone();

  private:
  const ::google::protobuf::RepeatedPtrField<::AnimBone_proto>& _internal_pobone() const;
  ::google::protobuf::RepeatedPtrField<::AnimBone_proto>* PROTOBUF_NONNULL _internal_mutable_pobone();
  public:
  const ::AnimBone_proto& pobone(int index) const;
  ::AnimBone_proto* PROTOBUF_NONNULL add_pobone();
  const ::google::protobuf::RepeatedPtrField<::AnimBone_proto>& pobone() const;
  // optional uint32 keyFrame = 1;
  bool has_keyframe() const;
  void clear_keyframe() ;
  ::uint32_t keyframe() const;
  void set_keyframe(::uint32_t value);

  private:
  ::uint32_t _internal_keyframe() const;
  void _internal_set_keyframe(::uint32_t value);

  public:
  // optional uint32 numNodes = 2;
  bool has_numnodes() const;
  void clear_numnodes() ;
  ::uint32_t numnodes() const;
  void set_numnodes(::uint32_t value);

  private:
  ::uint32_t _internal_numnodes() const;
  void _internal_set_numnodes(::uint32_t value);

  public:
  // optional float keyTime = 3;
  bool has_keytime() const;
  void clear_keytime() ;
  float keytime() const;
  void set_keytime(float value);

  private:
  float _internal_keytime() const;
  void _internal_set_keytime(float value);

  public:
  // optional int32 keyTimeIndex = 4;
  bool has_keytimeindex() const;
  void clear_keytimeindex() ;
  ::int32_t keytimeindex() const;
  void set_keytimeindex(::int32_t value);

  private:
  ::int32_t _internal_keytimeindex() const;
  void _internal_set_keytimeindex(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:AnimFrameBucket_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AnimFrameBucket_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::AnimBone_proto > pobone_;
    ::uint32_t keyframe_;
    ::uint32_t numnodes_;
    float keytime_;
    ::int32_t keytimeindex_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AnimFrameBucket_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<22> AnimFrameBucket_proto_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AnimFrameBucket_proto

// optional uint32 keyFrame = 1;
inline bool AnimFrameBucket_proto::has_keyframe() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void AnimFrameBucket_proto::clear_keyframe() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keyframe_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::uint32_t AnimFrameBucket_proto::keyframe() const {
  // @@protoc_insertion_point(field_get:AnimFrameBucket_proto.keyFrame)
  return _internal_keyframe();
}
inline void AnimFrameBucket_proto::set_keyframe(::uint32_t value) {
  _internal_set_keyframe(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:AnimFrameBucket_proto.keyFrame)
}
inline ::uint32_t AnimFrameBucket_proto::_internal_keyframe() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.keyframe_;
}
inline void AnimFrameBucket_proto::_internal_set_keyframe(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keyframe_ = value;
}

// optional uint32 numNodes = 2;
inline bool AnimFrameBucket_proto::has_numnodes() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void AnimFrameBucket_proto::clear_numnodes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numnodes_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint32_t AnimFrameBucket_proto::numnodes() const {
  // @@protoc_insertion_point(field_get:AnimFrameBucket_proto.numNodes)
  return _internal_numnodes();
}
inline void AnimFrameBucket_proto::set_numnodes(::uint32_t value) {
  _internal_set_numnodes(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:AnimFrameBucket_proto.numNodes)
}
inline ::uint32_t AnimFrameBucket_proto::_internal_numnodes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numnodes_;
}
inline void AnimFrameBucket_proto::_internal_set_numnodes(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numnodes_ = value;
}

// optional float keyTime = 3;
inline bool AnimFrameBucket_proto::has_keytime() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  return value;
}
inline void AnimFrameBucket_proto::clear_keytime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keytime_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline float AnimFrameBucket_proto::keytime() const {
  // @@protoc_insertion_point(field_get:AnimFrameBucket_proto.keyTime)
  return _internal_keytime();
}
inline void AnimFrameBucket_proto::set_keytime(float value) {
  _internal_set_keytime(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:AnimFrameBucket_proto.keyTime)
}
inline float AnimFrameBucket_proto::_internal_keytime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.keytime_;
}
inline void AnimFrameBucket_proto::_internal_set_keytime(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keytime_ = value;
}

// optional int32 keyTimeIndex = 4;
inline bool AnimFrameBucket_proto::has_keytimeindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008U) != 0;
  return value;
}
inline void AnimFrameBucket_proto::clear_keytimeindex() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keytimeindex_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008U;
}
inline ::int32_t AnimFrameBucket_proto::keytimeindex() const {
  // @@protoc_insertion_point(field_get:AnimFrameBucket_proto.keyTimeIndex)
  return _internal_keytimeindex();
}
inline void AnimFrameBucket_proto::set_keytimeindex(::int32_t value) {
  _internal_set_keytimeindex(value);
  _impl_._has_bits_[0] |= 0x00000008U;
  // @@protoc_insertion_point(field_set:AnimFrameBucket_proto.keyTimeIndex)
}
inline ::int32_t AnimFrameBucket_proto::_internal_keytimeindex() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.keytimeindex_;
}
inline void AnimFrameBucket_proto::_internal_set_keytimeindex(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.keytimeindex_ = value;
}

// repeated .AnimBone_proto poBone = 5;
inline int AnimFrameBucket_proto::_internal_pobone_size() const {
  return _internal_pobone().size();
}
inline int AnimFrameBucket_proto::pobone_size() const {
  return _internal_pobone_size();
}
inline ::AnimBone_proto* PROTOBUF_NONNULL AnimFrameBucket_proto::mutable_pobone(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:AnimFrameBucket_proto.poBone)
  return _internal_mutable_pobone()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::AnimBone_proto>* PROTOBUF_NONNULL AnimFrameBucket_proto::mutable_pobone()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:AnimFrameBucket_proto.poBone)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pobone();
}
inline const ::AnimBone_proto& AnimFrameBucket_proto::pobone(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AnimFrameBucket_proto.poBone)
  return _internal_pobone().Get(index);
}
inline ::AnimBone_proto* PROTOBUF_NONNULL AnimFrameBucket_proto::add_pobone()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::AnimBone_proto* _add = _internal_mutable_pobone()->Add();
  // @@protoc_insertion_point(field_add:AnimFrameBucket_proto.poBone)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::AnimBone_proto>& AnimFrameBucket_proto::pobone() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:AnimFrameBucket_proto.poBone)
  return _internal_pobone();
}
inline const ::google::protobuf::RepeatedPtrField<::AnimBone_proto>&
AnimFrameBucket_proto::_internal_pobone() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pobone_;
}
inline ::google::protobuf::RepeatedPtrField<::AnimBone_proto>* PROTOBUF_NONNULL
AnimFrameBucket_proto::_internal_mutable_pobone() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pobone_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // AnimFrameBucket_2eproto_2epb_2eh
