// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AnimBone.proto
// Protobuf C++ Version: 6.32.0-dev

#include "AnimBone.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr AnimBone_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        s_{nullptr},
        q_{nullptr},
        t_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR AnimBone_proto::AnimBone_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(AnimBone_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AnimBone_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnimBone_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnimBone_protoDefaultTypeInternal() {}
  union {
    AnimBone_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnimBone_protoDefaultTypeInternal _AnimBone_proto_default_instance_;
// ===================================================================

class AnimBone_proto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AnimBone_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AnimBone_proto, _impl_._has_bits_);
};

void AnimBone_proto::clear_s() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.s_ != nullptr) _impl_.s_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
void AnimBone_proto::clear_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.q_ != nullptr) _impl_.q_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
void AnimBone_proto::clear_t() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.t_ != nullptr) _impl_.t_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004U;
}
AnimBone_proto::AnimBone_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, AnimBone_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AnimBone_proto)
}
PROTOBUF_NDEBUG_INLINE AnimBone_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::AnimBone_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

AnimBone_proto::AnimBone_proto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AnimBone_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, AnimBone_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AnimBone_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.s_ = ((cached_has_bits & 0x00000001U) != 0)
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.s_)
                : nullptr;
  _impl_.q_ = ((cached_has_bits & 0x00000002U) != 0)
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.q_)
                : nullptr;
  _impl_.t_ = ((cached_has_bits & 0x00000004U) != 0)
                ? ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.t_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:AnimBone_proto)
}
PROTOBUF_NDEBUG_INLINE AnimBone_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void AnimBone_proto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, s_),
           0,
           offsetof(Impl_, t_) -
               offsetof(Impl_, s_) +
               sizeof(Impl_::t_));
}
AnimBone_proto::~AnimBone_proto() {
  // @@protoc_insertion_point(destructor:AnimBone_proto)
  SharedDtor(*this);
}
inline void AnimBone_proto::SharedDtor(MessageLite& self) {
  AnimBone_proto& this_ = static_cast<AnimBone_proto&>(self);
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.s_;
  delete this_._impl_.q_;
  delete this_._impl_.t_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AnimBone_proto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AnimBone_proto(arena);
}
constexpr auto AnimBone_proto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(AnimBone_proto),
                                            alignof(AnimBone_proto));
}
constexpr auto AnimBone_proto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<15>{
      {
          &_AnimBone_proto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &AnimBone_proto::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<AnimBone_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AnimBone_proto::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<AnimBone_proto>(), &AnimBone_proto::ByteSizeLong,
              &AnimBone_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AnimBone_proto, _impl_._cached_size_),
          true,
      },
      "AnimBone_proto",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<15> AnimBone_proto_class_data_ =
    AnimBone_proto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AnimBone_proto::GetClassData() const {
  return AnimBone_proto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 3, 0, 2>
AnimBone_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AnimBone_proto, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    AnimBone_proto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AnimBone_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional .AnimVec3_proto S = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(AnimBone_proto, _impl_.s_)}},
    // optional .AnimQuat_proto Q = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(AnimBone_proto, _impl_.q_)}},
    // optional .AnimVec3_proto T = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2, PROTOBUF_FIELD_OFFSET(AnimBone_proto, _impl_.t_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .AnimVec3_proto S = 1;
    {PROTOBUF_FIELD_OFFSET(AnimBone_proto, _impl_.s_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .AnimQuat_proto Q = 2;
    {PROTOBUF_FIELD_OFFSET(AnimBone_proto, _impl_.q_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .AnimVec3_proto T = 3;
    {PROTOBUF_FIELD_OFFSET(AnimBone_proto, _impl_.t_), _Internal::kHasBitsOffset + 2, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::AnimVec3_proto>()},
      {::_pbi::TcParser::GetTable<::AnimQuat_proto>()},
      {::_pbi::TcParser::GetTable<::AnimVec3_proto>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void AnimBone_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:AnimBone_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      ABSL_DCHECK(_impl_.s_ != nullptr);
      _impl_.s_->Clear();
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      ABSL_DCHECK(_impl_.q_ != nullptr);
      _impl_.q_->Clear();
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      ABSL_DCHECK(_impl_.t_ != nullptr);
      _impl_.t_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AnimBone_proto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AnimBone_proto& this_ = static_cast<const AnimBone_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AnimBone_proto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AnimBone_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AnimBone_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .AnimVec3_proto S = 1;
  if ((cached_has_bits & 0x00000001U) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.s_, this_._impl_.s_->GetCachedSize(), target,
        stream);
  }

  // optional .AnimQuat_proto Q = 2;
  if ((cached_has_bits & 0x00000002U) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.q_, this_._impl_.q_->GetCachedSize(), target,
        stream);
  }

  // optional .AnimVec3_proto T = 3;
  if ((cached_has_bits & 0x00000004U) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.t_, this_._impl_.t_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AnimBone_proto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AnimBone_proto::ByteSizeLong(const MessageLite& base) {
  const AnimBone_proto& this_ = static_cast<const AnimBone_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AnimBone_proto::ByteSizeLong() const {
  const AnimBone_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AnimBone_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    // optional .AnimVec3_proto S = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.s_);
    }
    // optional .AnimQuat_proto Q = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.q_);
    }
    // optional .AnimVec3_proto T = 3;
    if ((cached_has_bits & 0x00000004U) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.t_);
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void AnimBone_proto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AnimBone_proto*>(&to_msg);
  auto& from = static_cast<const AnimBone_proto&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:AnimBone_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      ABSL_DCHECK(from._impl_.s_ != nullptr);
      if (_this->_impl_.s_ == nullptr) {
        _this->_impl_.s_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.s_);
      } else {
        _this->_impl_.s_->MergeFrom(*from._impl_.s_);
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      ABSL_DCHECK(from._impl_.q_ != nullptr);
      if (_this->_impl_.q_ == nullptr) {
        _this->_impl_.q_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.q_);
      } else {
        _this->_impl_.q_->MergeFrom(*from._impl_.q_);
      }
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      ABSL_DCHECK(from._impl_.t_ != nullptr);
      if (_this->_impl_.t_ == nullptr) {
        _this->_impl_.t_ = ::google::protobuf::MessageLite::CopyConstruct(arena, *from._impl_.t_);
      } else {
        _this->_impl_.t_->MergeFrom(*from._impl_.t_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void AnimBone_proto::CopyFrom(const AnimBone_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AnimBone_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AnimBone_proto::InternalSwap(AnimBone_proto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AnimBone_proto, _impl_.t_)
      + sizeof(AnimBone_proto::_impl_.t_)
      - PROTOBUF_FIELD_OFFSET(AnimBone_proto, _impl_.s_)>(
          reinterpret_cast<char*>(&_impl_.s_),
          reinterpret_cast<char*>(&other->_impl_.s_));
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
