// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AnimClip.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef AnimClip_2eproto_2epb_2eh
#define AnimClip_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "AnimFrameBucket.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_AnimClip_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_AnimClip_2eproto {
  static const ::uint32_t offsets[];
};
class AnimClip_proto;
struct AnimClip_protoDefaultTypeInternal;
extern AnimClip_protoDefaultTypeInternal _AnimClip_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<15> AnimClip_proto_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class AnimClip_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:AnimClip_proto) */ {
 public:
  inline AnimClip_proto() : AnimClip_proto(nullptr) {}
  ~AnimClip_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AnimClip_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AnimClip_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AnimClip_proto(::google::protobuf::internal::ConstantInitialized);

  inline AnimClip_proto(const AnimClip_proto& from) : AnimClip_proto(nullptr, from) {}
  inline AnimClip_proto(AnimClip_proto&& from) noexcept
      : AnimClip_proto(nullptr, ::std::move(from)) {}
  inline AnimClip_proto& operator=(const AnimClip_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnimClip_proto& operator=(AnimClip_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const AnimClip_proto& default_instance() {
    return *reinterpret_cast<const AnimClip_proto*>(
        &_AnimClip_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AnimClip_proto& a, AnimClip_proto& b) { a.Swap(&b); }
  inline void Swap(AnimClip_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnimClip_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnimClip_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<AnimClip_proto>(arena);
  }
  void CopyFrom(const AnimClip_proto& from);
  void MergeFrom(const AnimClip_proto& from) { AnimClip_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AnimClip_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "AnimClip_proto"; }

 protected:
  explicit AnimClip_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AnimClip_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AnimClip_proto& from);
  AnimClip_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AnimClip_proto&& from) noexcept
      : AnimClip_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPoFrameBucketEntryFieldNumber = 4,
    kPVersionFieldNumber = 1,
    kNumKeyFramesFieldNumber = 2,
    kNumBonesFieldNumber = 3,
  };
  // repeated .AnimFrameBucket_proto poFrameBucketEntry = 4;
  int poframebucketentry_size() const;
  private:
  int _internal_poframebucketentry_size() const;

  public:
  void clear_poframebucketentry() ;
  ::AnimFrameBucket_proto* PROTOBUF_NONNULL mutable_poframebucketentry(int index);
  ::google::protobuf::RepeatedPtrField<::AnimFrameBucket_proto>* PROTOBUF_NONNULL mutable_poframebucketentry();

  private:
  const ::google::protobuf::RepeatedPtrField<::AnimFrameBucket_proto>& _internal_poframebucketentry() const;
  ::google::protobuf::RepeatedPtrField<::AnimFrameBucket_proto>* PROTOBUF_NONNULL _internal_mutable_poframebucketentry();
  public:
  const ::AnimFrameBucket_proto& poframebucketentry(int index) const;
  ::AnimFrameBucket_proto* PROTOBUF_NONNULL add_poframebucketentry();
  const ::google::protobuf::RepeatedPtrField<::AnimFrameBucket_proto>& poframebucketentry() const;
  // optional bytes pVersion = 1;
  bool has_pversion() const;
  void clear_pversion() ;
  const ::std::string& pversion() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pversion(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pversion();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pversion();
  void set_allocated_pversion(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pversion() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pversion(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pversion();

  public:
  // optional uint32 numKeyFrames = 2;
  bool has_numkeyframes() const;
  void clear_numkeyframes() ;
  ::uint32_t numkeyframes() const;
  void set_numkeyframes(::uint32_t value);

  private:
  ::uint32_t _internal_numkeyframes() const;
  void _internal_set_numkeyframes(::uint32_t value);

  public:
  // optional uint32 numBones = 3;
  bool has_numbones() const;
  void clear_numbones() ;
  ::uint32_t numbones() const;
  void set_numbones(::uint32_t value);

  private:
  ::uint32_t _internal_numbones() const;
  void _internal_set_numbones(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:AnimClip_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AnimClip_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::AnimFrameBucket_proto > poframebucketentry_;
    ::google::protobuf::internal::ArenaStringPtr pversion_;
    ::uint32_t numkeyframes_;
    ::uint32_t numbones_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AnimClip_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<15> AnimClip_proto_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AnimClip_proto

// optional bytes pVersion = 1;
inline bool AnimClip_proto::has_pversion() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void AnimClip_proto::clear_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pversion_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& AnimClip_proto::pversion() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AnimClip_proto.pVersion)
  return _internal_pversion();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void AnimClip_proto::set_pversion(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pversion_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:AnimClip_proto.pVersion)
}
inline ::std::string* PROTOBUF_NONNULL AnimClip_proto::mutable_pversion()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_pversion();
  // @@protoc_insertion_point(field_mutable:AnimClip_proto.pVersion)
  return _s;
}
inline const ::std::string& AnimClip_proto::_internal_pversion() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pversion_.Get();
}
inline void AnimClip_proto::_internal_set_pversion(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pversion_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL AnimClip_proto::_internal_mutable_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.pversion_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE AnimClip_proto::release_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:AnimClip_proto.pVersion)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.pversion_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pversion_.Set("", GetArena());
  }
  return released;
}
inline void AnimClip_proto::set_allocated_pversion(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.pversion_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pversion_.IsDefault()) {
    _impl_.pversion_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:AnimClip_proto.pVersion)
}

// optional uint32 numKeyFrames = 2;
inline bool AnimClip_proto::has_numkeyframes() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void AnimClip_proto::clear_numkeyframes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numkeyframes_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint32_t AnimClip_proto::numkeyframes() const {
  // @@protoc_insertion_point(field_get:AnimClip_proto.numKeyFrames)
  return _internal_numkeyframes();
}
inline void AnimClip_proto::set_numkeyframes(::uint32_t value) {
  _internal_set_numkeyframes(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:AnimClip_proto.numKeyFrames)
}
inline ::uint32_t AnimClip_proto::_internal_numkeyframes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numkeyframes_;
}
inline void AnimClip_proto::_internal_set_numkeyframes(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numkeyframes_ = value;
}

// optional uint32 numBones = 3;
inline bool AnimClip_proto::has_numbones() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  return value;
}
inline void AnimClip_proto::clear_numbones() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numbones_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline ::uint32_t AnimClip_proto::numbones() const {
  // @@protoc_insertion_point(field_get:AnimClip_proto.numBones)
  return _internal_numbones();
}
inline void AnimClip_proto::set_numbones(::uint32_t value) {
  _internal_set_numbones(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:AnimClip_proto.numBones)
}
inline ::uint32_t AnimClip_proto::_internal_numbones() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numbones_;
}
inline void AnimClip_proto::_internal_set_numbones(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numbones_ = value;
}

// repeated .AnimFrameBucket_proto poFrameBucketEntry = 4;
inline int AnimClip_proto::_internal_poframebucketentry_size() const {
  return _internal_poframebucketentry().size();
}
inline int AnimClip_proto::poframebucketentry_size() const {
  return _internal_poframebucketentry_size();
}
inline ::AnimFrameBucket_proto* PROTOBUF_NONNULL AnimClip_proto::mutable_poframebucketentry(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:AnimClip_proto.poFrameBucketEntry)
  return _internal_mutable_poframebucketentry()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::AnimFrameBucket_proto>* PROTOBUF_NONNULL AnimClip_proto::mutable_poframebucketentry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:AnimClip_proto.poFrameBucketEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_poframebucketentry();
}
inline const ::AnimFrameBucket_proto& AnimClip_proto::poframebucketentry(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AnimClip_proto.poFrameBucketEntry)
  return _internal_poframebucketentry().Get(index);
}
inline ::AnimFrameBucket_proto* PROTOBUF_NONNULL AnimClip_proto::add_poframebucketentry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::AnimFrameBucket_proto* _add = _internal_mutable_poframebucketentry()->Add();
  // @@protoc_insertion_point(field_add:AnimClip_proto.poFrameBucketEntry)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::AnimFrameBucket_proto>& AnimClip_proto::poframebucketentry() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:AnimClip_proto.poFrameBucketEntry)
  return _internal_poframebucketentry();
}
inline const ::google::protobuf::RepeatedPtrField<::AnimFrameBucket_proto>&
AnimClip_proto::_internal_poframebucketentry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.poframebucketentry_;
}
inline ::google::protobuf::RepeatedPtrField<::AnimFrameBucket_proto>* PROTOBUF_NONNULL
AnimClip_proto::_internal_mutable_poframebucketentry() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.poframebucketentry_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // AnimClip_2eproto_2epb_2eh
