// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AnimClip.proto
// Protobuf C++ Version: 6.32.0-dev

#include "AnimClip.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr AnimClip_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        poframebucketentry_{},
        pversion_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        numkeyframes_{0u},
        numnodes_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR AnimClip_proto::AnimClip_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(AnimClip_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AnimClip_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnimClip_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnimClip_protoDefaultTypeInternal() {}
  union {
    AnimClip_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnimClip_protoDefaultTypeInternal _AnimClip_proto_default_instance_;
// ===================================================================

class AnimClip_proto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AnimClip_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_._has_bits_);
};

void AnimClip_proto::clear_poframebucketentry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.poframebucketentry_.Clear();
}
AnimClip_proto::AnimClip_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, AnimClip_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AnimClip_proto)
}
PROTOBUF_NDEBUG_INLINE AnimClip_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::AnimClip_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        poframebucketentry_{visibility, arena, from.poframebucketentry_},
        pversion_(arena, from.pversion_) {}

AnimClip_proto::AnimClip_proto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const AnimClip_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, AnimClip_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AnimClip_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, numkeyframes_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, numkeyframes_),
           offsetof(Impl_, numnodes_) -
               offsetof(Impl_, numkeyframes_) +
               sizeof(Impl_::numnodes_));

  // @@protoc_insertion_point(copy_constructor:AnimClip_proto)
}
PROTOBUF_NDEBUG_INLINE AnimClip_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        poframebucketentry_{visibility, arena},
        pversion_(arena) {}

inline void AnimClip_proto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, numkeyframes_),
           0,
           offsetof(Impl_, numnodes_) -
               offsetof(Impl_, numkeyframes_) +
               sizeof(Impl_::numnodes_));
}
AnimClip_proto::~AnimClip_proto() {
  // @@protoc_insertion_point(destructor:AnimClip_proto)
  SharedDtor(*this);
}
inline void AnimClip_proto::SharedDtor(MessageLite& self) {
  AnimClip_proto& this_ = static_cast<AnimClip_proto&>(self);
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.pversion_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AnimClip_proto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AnimClip_proto(arena);
}
constexpr auto AnimClip_proto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_.poframebucketentry_) +
          decltype(AnimClip_proto::_impl_.poframebucketentry_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(AnimClip_proto), alignof(AnimClip_proto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&AnimClip_proto::PlacementNew_,
                                 sizeof(AnimClip_proto),
                                 alignof(AnimClip_proto));
  }
}
constexpr auto AnimClip_proto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<15>{
      {
          &_AnimClip_proto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &AnimClip_proto::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<AnimClip_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AnimClip_proto::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<AnimClip_proto>(), &AnimClip_proto::ByteSizeLong,
              &AnimClip_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_._cached_size_),
          true,
      },
      "AnimClip_proto",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<15> AnimClip_proto_class_data_ =
    AnimClip_proto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AnimClip_proto::GetClassData() const {
  return AnimClip_proto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2>
AnimClip_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    AnimClip_proto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AnimClip_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .AnimFrameBucket_proto poFrameBucketEntry = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_.poframebucketentry_)}},
    // optional bytes pVersion = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_.pversion_)}},
    // optional uint32 numKeyFrames = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_.numkeyframes_)}},
    // optional uint32 numNodes = 3;
    {::_pbi::TcParser::FastV32S1,
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_.numnodes_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bytes pVersion = 1;
    {PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_.pversion_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional uint32 numKeyFrames = 2;
    {PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_.numkeyframes_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 numNodes = 3;
    {PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_.numnodes_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated .AnimFrameBucket_proto poFrameBucketEntry = 4;
    {PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_.poframebucketentry_), -1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::AnimFrameBucket_proto>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void AnimClip_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:AnimClip_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.poframebucketentry_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.pversion_.ClearNonDefaultToEmpty();
  }
  if ((cached_has_bits & 0x00000006U) != 0) {
    ::memset(&_impl_.numkeyframes_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.numnodes_) -
        reinterpret_cast<char*>(&_impl_.numkeyframes_)) + sizeof(_impl_.numnodes_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AnimClip_proto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AnimClip_proto& this_ = static_cast<const AnimClip_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AnimClip_proto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AnimClip_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AnimClip_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional bytes pVersion = 1;
  if ((cached_has_bits & 0x00000001U) != 0) {
    const ::std::string& _s = this_._internal_pversion();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // optional uint32 numKeyFrames = 2;
  if ((cached_has_bits & 0x00000002U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_numkeyframes(), target);
  }

  // optional uint32 numNodes = 3;
  if ((cached_has_bits & 0x00000004U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_numnodes(), target);
  }

  // repeated .AnimFrameBucket_proto poFrameBucketEntry = 4;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_poframebucketentry_size());
       i < n; i++) {
    const auto& repfield = this_._internal_poframebucketentry().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            4, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AnimClip_proto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AnimClip_proto::ByteSizeLong(const MessageLite& base) {
  const AnimClip_proto& this_ = static_cast<const AnimClip_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AnimClip_proto::ByteSizeLong() const {
  const AnimClip_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AnimClip_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .AnimFrameBucket_proto poFrameBucketEntry = 4;
    {
      total_size += 1UL * this_._internal_poframebucketentry_size();
      for (const auto& msg : this_._internal_poframebucketentry()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    // optional bytes pVersion = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_pversion());
    }
    // optional uint32 numKeyFrames = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_numkeyframes());
    }
    // optional uint32 numNodes = 3;
    if ((cached_has_bits & 0x00000004U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_numnodes());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void AnimClip_proto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AnimClip_proto*>(&to_msg);
  auto& from = static_cast<const AnimClip_proto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AnimClip_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_poframebucketentry()->MergeFrom(
      from._internal_poframebucketentry());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _this->_internal_set_pversion(from._internal_pversion());
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _this->_impl_.numkeyframes_ = from._impl_.numkeyframes_;
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      _this->_impl_.numnodes_ = from._impl_.numnodes_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void AnimClip_proto::CopyFrom(const AnimClip_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AnimClip_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AnimClip_proto::InternalSwap(AnimClip_proto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.poframebucketentry_.InternalSwap(&other->_impl_.poframebucketentry_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pversion_, &other->_impl_.pversion_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_.numnodes_)
      + sizeof(AnimClip_proto::_impl_.numnodes_)
      - PROTOBUF_FIELD_OFFSET(AnimClip_proto, _impl_.numkeyframes_)>(
          reinterpret_cast<char*>(&_impl_.numkeyframes_),
          reinterpret_cast<char*>(&other->_impl_.numkeyframes_));
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
