// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AnimQuat.proto
// Protobuf C++ Version: 6.32.0-dev

#include "AnimQuat.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr AnimQuat_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        qx_{0},
        qy_{0},
        qz_{0},
        qw_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AnimQuat_proto::AnimQuat_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(AnimQuat_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AnimQuat_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AnimQuat_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AnimQuat_protoDefaultTypeInternal() {}
  union {
    AnimQuat_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AnimQuat_protoDefaultTypeInternal _AnimQuat_proto_default_instance_;
// ===================================================================

class AnimQuat_proto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<AnimQuat_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AnimQuat_proto, _impl_._has_bits_);
};

AnimQuat_proto::AnimQuat_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, AnimQuat_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:AnimQuat_proto)
}
AnimQuat_proto::AnimQuat_proto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AnimQuat_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, AnimQuat_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE AnimQuat_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void AnimQuat_proto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, qx_),
           0,
           offsetof(Impl_, qw_) -
               offsetof(Impl_, qx_) +
               sizeof(Impl_::qw_));
}
AnimQuat_proto::~AnimQuat_proto() {
  // @@protoc_insertion_point(destructor:AnimQuat_proto)
  SharedDtor(*this);
}
inline void AnimQuat_proto::SharedDtor(MessageLite& self) {
  AnimQuat_proto& this_ = static_cast<AnimQuat_proto&>(self);
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL AnimQuat_proto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AnimQuat_proto(arena);
}
constexpr auto AnimQuat_proto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(AnimQuat_proto),
                                            alignof(AnimQuat_proto));
}
constexpr auto AnimQuat_proto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<15>{
      {
          &_AnimQuat_proto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &AnimQuat_proto::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<AnimQuat_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AnimQuat_proto::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<AnimQuat_proto>(), &AnimQuat_proto::ByteSizeLong,
              &AnimQuat_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AnimQuat_proto, _impl_._cached_size_),
          true,
      },
      "AnimQuat_proto",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<15> AnimQuat_proto_class_data_ =
    AnimQuat_proto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AnimQuat_proto::GetClassData() const {
  return AnimQuat_proto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
AnimQuat_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AnimQuat_proto, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    AnimQuat_proto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::AnimQuat_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional float qw = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 3, 0, PROTOBUF_FIELD_OFFSET(AnimQuat_proto, _impl_.qw_)}},
    // optional float qx = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 0, 0, PROTOBUF_FIELD_OFFSET(AnimQuat_proto, _impl_.qx_)}},
    // optional float qy = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0, PROTOBUF_FIELD_OFFSET(AnimQuat_proto, _impl_.qy_)}},
    // optional float qz = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 2, 0, PROTOBUF_FIELD_OFFSET(AnimQuat_proto, _impl_.qz_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional float qx = 1;
    {PROTOBUF_FIELD_OFFSET(AnimQuat_proto, _impl_.qx_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float qy = 2;
    {PROTOBUF_FIELD_OFFSET(AnimQuat_proto, _impl_.qy_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float qz = 3;
    {PROTOBUF_FIELD_OFFSET(AnimQuat_proto, _impl_.qz_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float qw = 4;
    {PROTOBUF_FIELD_OFFSET(AnimQuat_proto, _impl_.qw_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void AnimQuat_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:AnimQuat_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fU) != 0) {
    ::memset(&_impl_.qx_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.qw_) -
        reinterpret_cast<char*>(&_impl_.qx_)) + sizeof(_impl_.qw_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AnimQuat_proto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AnimQuat_proto& this_ = static_cast<const AnimQuat_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AnimQuat_proto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AnimQuat_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:AnimQuat_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional float qx = 1;
  if ((cached_has_bits & 0x00000001U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this_._internal_qx(), target);
  }

  // optional float qy = 2;
  if ((cached_has_bits & 0x00000002U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this_._internal_qy(), target);
  }

  // optional float qz = 3;
  if ((cached_has_bits & 0x00000004U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this_._internal_qz(), target);
  }

  // optional float qw = 4;
  if ((cached_has_bits & 0x00000008U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this_._internal_qw(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AnimQuat_proto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AnimQuat_proto::ByteSizeLong(const MessageLite& base) {
  const AnimQuat_proto& this_ = static_cast<const AnimQuat_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AnimQuat_proto::ByteSizeLong() const {
  const AnimQuat_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:AnimQuat_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x0000000fU & cached_has_bits) * 5;
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void AnimQuat_proto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AnimQuat_proto*>(&to_msg);
  auto& from = static_cast<const AnimQuat_proto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:AnimQuat_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fU) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _this->_impl_.qx_ = from._impl_.qx_;
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _this->_impl_.qy_ = from._impl_.qy_;
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      _this->_impl_.qz_ = from._impl_.qz_;
    }
    if ((cached_has_bits & 0x00000008U) != 0) {
      _this->_impl_.qw_ = from._impl_.qw_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void AnimQuat_proto::CopyFrom(const AnimQuat_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:AnimQuat_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AnimQuat_proto::InternalSwap(AnimQuat_proto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AnimQuat_proto, _impl_.qw_)
      + sizeof(AnimQuat_proto::_impl_.qw_)
      - PROTOBUF_FIELD_OFFSET(AnimQuat_proto, _impl_.qx_)>(
          reinterpret_cast<char*>(&_impl_.qx_),
          reinterpret_cast<char*>(&other->_impl_.qx_));
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
