// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: AnimBone.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef AnimBone_2eproto_2epb_2eh
#define AnimBone_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "AnimVec3.pb.h"
#include "AnimQuat.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_AnimBone_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_AnimBone_2eproto {
  static const ::uint32_t offsets[];
};
class AnimBone_proto;
struct AnimBone_protoDefaultTypeInternal;
extern AnimBone_protoDefaultTypeInternal _AnimBone_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<15> AnimBone_proto_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class AnimBone_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:AnimBone_proto) */ {
 public:
  inline AnimBone_proto() : AnimBone_proto(nullptr) {}
  ~AnimBone_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AnimBone_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AnimBone_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AnimBone_proto(::google::protobuf::internal::ConstantInitialized);

  inline AnimBone_proto(const AnimBone_proto& from) : AnimBone_proto(nullptr, from) {}
  inline AnimBone_proto(AnimBone_proto&& from) noexcept
      : AnimBone_proto(nullptr, ::std::move(from)) {}
  inline AnimBone_proto& operator=(const AnimBone_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline AnimBone_proto& operator=(AnimBone_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const AnimBone_proto& default_instance() {
    return *reinterpret_cast<const AnimBone_proto*>(
        &_AnimBone_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AnimBone_proto& a, AnimBone_proto& b) { a.Swap(&b); }
  inline void Swap(AnimBone_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AnimBone_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AnimBone_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<AnimBone_proto>(arena);
  }
  void CopyFrom(const AnimBone_proto& from);
  void MergeFrom(const AnimBone_proto& from) { AnimBone_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AnimBone_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "AnimBone_proto"; }

 protected:
  explicit AnimBone_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AnimBone_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AnimBone_proto& from);
  AnimBone_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AnimBone_proto&& from) noexcept
      : AnimBone_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSFieldNumber = 1,
    kQFieldNumber = 2,
    kTFieldNumber = 3,
  };
  // optional .AnimVec3_proto S = 1;
  bool has_s() const;
  void clear_s() ;
  const ::AnimVec3_proto& s() const;
  [[nodiscard]] ::AnimVec3_proto* PROTOBUF_NULLABLE release_s();
  ::AnimVec3_proto* PROTOBUF_NONNULL mutable_s();
  void set_allocated_s(::AnimVec3_proto* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_s(::AnimVec3_proto* PROTOBUF_NULLABLE value);
  ::AnimVec3_proto* PROTOBUF_NULLABLE unsafe_arena_release_s();

  private:
  const ::AnimVec3_proto& _internal_s() const;
  ::AnimVec3_proto* PROTOBUF_NONNULL _internal_mutable_s();

  public:
  // optional .AnimQuat_proto Q = 2;
  bool has_q() const;
  void clear_q() ;
  const ::AnimQuat_proto& q() const;
  [[nodiscard]] ::AnimQuat_proto* PROTOBUF_NULLABLE release_q();
  ::AnimQuat_proto* PROTOBUF_NONNULL mutable_q();
  void set_allocated_q(::AnimQuat_proto* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_q(::AnimQuat_proto* PROTOBUF_NULLABLE value);
  ::AnimQuat_proto* PROTOBUF_NULLABLE unsafe_arena_release_q();

  private:
  const ::AnimQuat_proto& _internal_q() const;
  ::AnimQuat_proto* PROTOBUF_NONNULL _internal_mutable_q();

  public:
  // optional .AnimVec3_proto T = 3;
  bool has_t() const;
  void clear_t() ;
  const ::AnimVec3_proto& t() const;
  [[nodiscard]] ::AnimVec3_proto* PROTOBUF_NULLABLE release_t();
  ::AnimVec3_proto* PROTOBUF_NONNULL mutable_t();
  void set_allocated_t(::AnimVec3_proto* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_t(::AnimVec3_proto* PROTOBUF_NULLABLE value);
  ::AnimVec3_proto* PROTOBUF_NULLABLE unsafe_arena_release_t();

  private:
  const ::AnimVec3_proto& _internal_t() const;
  ::AnimVec3_proto* PROTOBUF_NONNULL _internal_mutable_t();

  public:
  // @@protoc_insertion_point(class_scope:AnimBone_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AnimBone_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::AnimVec3_proto* PROTOBUF_NULLABLE s_;
    ::AnimQuat_proto* PROTOBUF_NULLABLE q_;
    ::AnimVec3_proto* PROTOBUF_NULLABLE t_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_AnimBone_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<15> AnimBone_proto_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AnimBone_proto

// optional .AnimVec3_proto S = 1;
inline bool AnimBone_proto::has_s() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.s_ != nullptr);
  return value;
}
inline const ::AnimVec3_proto& AnimBone_proto::_internal_s() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::AnimVec3_proto* p = _impl_.s_;
  return p != nullptr ? *p : reinterpret_cast<const ::AnimVec3_proto&>(::_AnimVec3_proto_default_instance_);
}
inline const ::AnimVec3_proto& AnimBone_proto::s() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AnimBone_proto.S)
  return _internal_s();
}
inline void AnimBone_proto::unsafe_arena_set_allocated_s(
    ::AnimVec3_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.s_);
  }
  _impl_.s_ = reinterpret_cast<::AnimVec3_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AnimBone_proto.S)
}
inline ::AnimVec3_proto* PROTOBUF_NULLABLE AnimBone_proto::release_s() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::AnimVec3_proto* released = _impl_.s_;
  _impl_.s_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::AnimVec3_proto* PROTOBUF_NULLABLE AnimBone_proto::unsafe_arena_release_s() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:AnimBone_proto.S)

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::AnimVec3_proto* temp = _impl_.s_;
  _impl_.s_ = nullptr;
  return temp;
}
inline ::AnimVec3_proto* PROTOBUF_NONNULL AnimBone_proto::_internal_mutable_s() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.s_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::AnimVec3_proto>(GetArena());
    _impl_.s_ = reinterpret_cast<::AnimVec3_proto*>(p);
  }
  return _impl_.s_;
}
inline ::AnimVec3_proto* PROTOBUF_NONNULL AnimBone_proto::mutable_s()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001U;
  ::AnimVec3_proto* _msg = _internal_mutable_s();
  // @@protoc_insertion_point(field_mutable:AnimBone_proto.S)
  return _msg;
}
inline void AnimBone_proto::set_allocated_s(::AnimVec3_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.s_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }

  _impl_.s_ = reinterpret_cast<::AnimVec3_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:AnimBone_proto.S)
}

// optional .AnimQuat_proto Q = 2;
inline bool AnimBone_proto::has_q() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.q_ != nullptr);
  return value;
}
inline const ::AnimQuat_proto& AnimBone_proto::_internal_q() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::AnimQuat_proto* p = _impl_.q_;
  return p != nullptr ? *p : reinterpret_cast<const ::AnimQuat_proto&>(::_AnimQuat_proto_default_instance_);
}
inline const ::AnimQuat_proto& AnimBone_proto::q() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AnimBone_proto.Q)
  return _internal_q();
}
inline void AnimBone_proto::unsafe_arena_set_allocated_q(
    ::AnimQuat_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.q_);
  }
  _impl_.q_ = reinterpret_cast<::AnimQuat_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AnimBone_proto.Q)
}
inline ::AnimQuat_proto* PROTOBUF_NULLABLE AnimBone_proto::release_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002U;
  ::AnimQuat_proto* released = _impl_.q_;
  _impl_.q_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::AnimQuat_proto* PROTOBUF_NULLABLE AnimBone_proto::unsafe_arena_release_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:AnimBone_proto.Q)

  _impl_._has_bits_[0] &= ~0x00000002U;
  ::AnimQuat_proto* temp = _impl_.q_;
  _impl_.q_ = nullptr;
  return temp;
}
inline ::AnimQuat_proto* PROTOBUF_NONNULL AnimBone_proto::_internal_mutable_q() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.q_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::AnimQuat_proto>(GetArena());
    _impl_.q_ = reinterpret_cast<::AnimQuat_proto*>(p);
  }
  return _impl_.q_;
}
inline ::AnimQuat_proto* PROTOBUF_NONNULL AnimBone_proto::mutable_q()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002U;
  ::AnimQuat_proto* _msg = _internal_mutable_q();
  // @@protoc_insertion_point(field_mutable:AnimBone_proto.Q)
  return _msg;
}
inline void AnimBone_proto::set_allocated_q(::AnimQuat_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.q_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }

  _impl_.q_ = reinterpret_cast<::AnimQuat_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:AnimBone_proto.Q)
}

// optional .AnimVec3_proto T = 3;
inline bool AnimBone_proto::has_t() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.t_ != nullptr);
  return value;
}
inline const ::AnimVec3_proto& AnimBone_proto::_internal_t() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::AnimVec3_proto* p = _impl_.t_;
  return p != nullptr ? *p : reinterpret_cast<const ::AnimVec3_proto&>(::_AnimVec3_proto_default_instance_);
}
inline const ::AnimVec3_proto& AnimBone_proto::t() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:AnimBone_proto.T)
  return _internal_t();
}
inline void AnimBone_proto::unsafe_arena_set_allocated_t(
    ::AnimVec3_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.t_);
  }
  _impl_.t_ = reinterpret_cast<::AnimVec3_proto*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:AnimBone_proto.T)
}
inline ::AnimVec3_proto* PROTOBUF_NULLABLE AnimBone_proto::release_t() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004U;
  ::AnimVec3_proto* released = _impl_.t_;
  _impl_.t_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::AnimVec3_proto* PROTOBUF_NULLABLE AnimBone_proto::unsafe_arena_release_t() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:AnimBone_proto.T)

  _impl_._has_bits_[0] &= ~0x00000004U;
  ::AnimVec3_proto* temp = _impl_.t_;
  _impl_.t_ = nullptr;
  return temp;
}
inline ::AnimVec3_proto* PROTOBUF_NONNULL AnimBone_proto::_internal_mutable_t() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.t_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::AnimVec3_proto>(GetArena());
    _impl_.t_ = reinterpret_cast<::AnimVec3_proto*>(p);
  }
  return _impl_.t_;
}
inline ::AnimVec3_proto* PROTOBUF_NONNULL AnimBone_proto::mutable_t()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004U;
  ::AnimVec3_proto* _msg = _internal_mutable_t();
  // @@protoc_insertion_point(field_mutable:AnimBone_proto.T)
  return _msg;
}
inline void AnimBone_proto::set_allocated_t(::AnimVec3_proto* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.t_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004U;
  }

  _impl_.t_ = reinterpret_cast<::AnimVec3_proto*>(value);
  // @@protoc_insertion_point(field_set_allocated:AnimBone_proto.T)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // AnimBone_2eproto_2epb_2eh
