// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FontData.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef FontData_2eproto_2epb_2eh
#define FontData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "FontEntry.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_FontData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_FontData_2eproto {
  static const ::uint32_t offsets[];
};
class FontData_proto;
struct FontData_protoDefaultTypeInternal;
extern FontData_protoDefaultTypeInternal _FontData_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<15> FontData_proto_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class FontData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:FontData_proto) */ {
 public:
  inline FontData_proto() : FontData_proto(nullptr) {}
  ~FontData_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FontData_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FontData_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FontData_proto(::google::protobuf::internal::ConstantInitialized);

  inline FontData_proto(const FontData_proto& from) : FontData_proto(nullptr, from) {}
  inline FontData_proto(FontData_proto&& from) noexcept
      : FontData_proto(nullptr, ::std::move(from)) {}
  inline FontData_proto& operator=(const FontData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline FontData_proto& operator=(FontData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const FontData_proto& default_instance() {
    return *reinterpret_cast<const FontData_proto*>(
        &_FontData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(FontData_proto& a, FontData_proto& b) { a.Swap(&b); }
  inline void Swap(FontData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FontData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FontData_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<FontData_proto>(arena);
  }
  void CopyFrom(const FontData_proto& from);
  void MergeFrom(const FontData_proto& from) { FontData_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FontData_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "FontData_proto"; }

 protected:
  explicit FontData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FontData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FontData_proto& from);
  FontData_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FontData_proto&& from) noexcept
      : FontData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPoFontEntryFieldNumber = 3,
    kPVersionFieldNumber = 1,
    kNumKeysFieldNumber = 2,
  };
  // repeated .FontEntry_proto poFontEntry = 3;
  int pofontentry_size() const;
  private:
  int _internal_pofontentry_size() const;

  public:
  void clear_pofontentry() ;
  ::FontEntry_proto* PROTOBUF_NONNULL mutable_pofontentry(int index);
  ::google::protobuf::RepeatedPtrField<::FontEntry_proto>* PROTOBUF_NONNULL mutable_pofontentry();

  private:
  const ::google::protobuf::RepeatedPtrField<::FontEntry_proto>& _internal_pofontentry() const;
  ::google::protobuf::RepeatedPtrField<::FontEntry_proto>* PROTOBUF_NONNULL _internal_mutable_pofontentry();
  public:
  const ::FontEntry_proto& pofontentry(int index) const;
  ::FontEntry_proto* PROTOBUF_NONNULL add_pofontentry();
  const ::google::protobuf::RepeatedPtrField<::FontEntry_proto>& pofontentry() const;
  // optional bytes pVersion = 1;
  bool has_pversion() const;
  void clear_pversion() ;
  const ::std::string& pversion() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pversion(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pversion();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pversion();
  void set_allocated_pversion(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pversion() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pversion(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pversion();

  public:
  // optional uint32 numKeys = 2;
  bool has_numkeys() const;
  void clear_numkeys() ;
  ::uint32_t numkeys() const;
  void set_numkeys(::uint32_t value);

  private:
  ::uint32_t _internal_numkeys() const;
  void _internal_set_numkeys(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:FontData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FontData_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::FontEntry_proto > pofontentry_;
    ::google::protobuf::internal::ArenaStringPtr pversion_;
    ::uint32_t numkeys_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_FontData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<15> FontData_proto_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// FontData_proto

// optional bytes pVersion = 1;
inline bool FontData_proto::has_pversion() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void FontData_proto::clear_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pversion_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& FontData_proto::pversion() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FontData_proto.pVersion)
  return _internal_pversion();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FontData_proto::set_pversion(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pversion_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FontData_proto.pVersion)
}
inline ::std::string* PROTOBUF_NONNULL FontData_proto::mutable_pversion()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_pversion();
  // @@protoc_insertion_point(field_mutable:FontData_proto.pVersion)
  return _s;
}
inline const ::std::string& FontData_proto::_internal_pversion() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pversion_.Get();
}
inline void FontData_proto::_internal_set_pversion(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pversion_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FontData_proto::_internal_mutable_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.pversion_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FontData_proto::release_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FontData_proto.pVersion)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.pversion_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pversion_.Set("", GetArena());
  }
  return released;
}
inline void FontData_proto::set_allocated_pversion(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.pversion_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pversion_.IsDefault()) {
    _impl_.pversion_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FontData_proto.pVersion)
}

// optional uint32 numKeys = 2;
inline bool FontData_proto::has_numkeys() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void FontData_proto::clear_numkeys() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numkeys_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint32_t FontData_proto::numkeys() const {
  // @@protoc_insertion_point(field_get:FontData_proto.numKeys)
  return _internal_numkeys();
}
inline void FontData_proto::set_numkeys(::uint32_t value) {
  _internal_set_numkeys(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:FontData_proto.numKeys)
}
inline ::uint32_t FontData_proto::_internal_numkeys() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numkeys_;
}
inline void FontData_proto::_internal_set_numkeys(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numkeys_ = value;
}

// repeated .FontEntry_proto poFontEntry = 3;
inline int FontData_proto::_internal_pofontentry_size() const {
  return _internal_pofontentry().size();
}
inline int FontData_proto::pofontentry_size() const {
  return _internal_pofontentry_size();
}
inline ::FontEntry_proto* PROTOBUF_NONNULL FontData_proto::mutable_pofontentry(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:FontData_proto.poFontEntry)
  return _internal_mutable_pofontentry()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::FontEntry_proto>* PROTOBUF_NONNULL FontData_proto::mutable_pofontentry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:FontData_proto.poFontEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pofontentry();
}
inline const ::FontEntry_proto& FontData_proto::pofontentry(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FontData_proto.poFontEntry)
  return _internal_pofontentry().Get(index);
}
inline ::FontEntry_proto* PROTOBUF_NONNULL FontData_proto::add_pofontentry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::FontEntry_proto* _add = _internal_mutable_pofontentry()->Add();
  // @@protoc_insertion_point(field_add:FontData_proto.poFontEntry)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::FontEntry_proto>& FontData_proto::pofontentry() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:FontData_proto.poFontEntry)
  return _internal_pofontentry();
}
inline const ::google::protobuf::RepeatedPtrField<::FontEntry_proto>&
FontData_proto::_internal_pofontentry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pofontentry_;
}
inline ::google::protobuf::RepeatedPtrField<::FontEntry_proto>* PROTOBUF_NONNULL
FontData_proto::_internal_mutable_pofontentry() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pofontentry_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // FontData_2eproto_2epb_2eh
