// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: JointData.proto
// Protobuf C++ Version: 6.32.0-dev

#include "JointData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr JointData_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pojointentry_{},
        _pojointentry_cached_byte_size_{0},
        numjoints_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR JointData_proto::JointData_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(JointData_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct JointData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JointData_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JointData_protoDefaultTypeInternal() {}
  union {
    JointData_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JointData_protoDefaultTypeInternal _JointData_proto_default_instance_;
// ===================================================================

class JointData_proto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<JointData_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_._has_bits_);
};

JointData_proto::JointData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, JointData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:JointData_proto)
}
PROTOBUF_NDEBUG_INLINE JointData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::JointData_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pojointentry_{visibility, arena, from.pojointentry_},
        _pojointentry_cached_byte_size_{0} {}

JointData_proto::JointData_proto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const JointData_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, JointData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  JointData_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.numjoints_ = from._impl_.numjoints_;

  // @@protoc_insertion_point(copy_constructor:JointData_proto)
}
PROTOBUF_NDEBUG_INLINE JointData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        pojointentry_{visibility, arena},
        _pojointentry_cached_byte_size_{0} {}

inline void JointData_proto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.numjoints_ = {};
}
JointData_proto::~JointData_proto() {
  // @@protoc_insertion_point(destructor:JointData_proto)
  SharedDtor(*this);
}
inline void JointData_proto::SharedDtor(MessageLite& self) {
  JointData_proto& this_ = static_cast<JointData_proto&>(self);
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL JointData_proto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) JointData_proto(arena);
}
constexpr auto JointData_proto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_.pojointentry_) +
          decltype(JointData_proto::_impl_.pojointentry_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(JointData_proto), alignof(JointData_proto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&JointData_proto::PlacementNew_,
                                 sizeof(JointData_proto),
                                 alignof(JointData_proto));
  }
}
constexpr auto JointData_proto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<16>{
      {
          &_JointData_proto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &JointData_proto::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<JointData_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &JointData_proto::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<JointData_proto>(), &JointData_proto::ByteSizeLong,
              &JointData_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_._cached_size_),
          true,
      },
      "JointData_proto",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<16> JointData_proto_class_data_ =
    JointData_proto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
JointData_proto::GetClassData() const {
  return JointData_proto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
JointData_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    JointData_proto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::JointData_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated uint32 poJointEntry = 2;
    {::_pbi::TcParser::FastV32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_.pojointentry_)}},
    // optional uint32 numJoints = 1;
    {::_pbi::TcParser::FastV32S1,
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_.numjoints_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 numJoints = 1;
    {PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_.numjoints_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated uint32 poJointEntry = 2;
    {PROTOBUF_FIELD_OFFSET(JointData_proto, _impl_.pojointentry_), -1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void JointData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:JointData_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pojointentry_.Clear();
  _impl_.numjoints_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL JointData_proto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const JointData_proto& this_ = static_cast<const JointData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL JointData_proto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const JointData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:JointData_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 numJoints = 1;
  if ((cached_has_bits & 0x00000001U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_numjoints(), target);
  }

  // repeated uint32 poJointEntry = 2;
  {
    int byte_size = this_._impl_._pojointentry_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          2, this_._internal_pojointentry(), byte_size, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:JointData_proto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t JointData_proto::ByteSizeLong(const MessageLite& base) {
  const JointData_proto& this_ = static_cast<const JointData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t JointData_proto::ByteSizeLong() const {
  const JointData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:JointData_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated uint32 poJointEntry = 2;
    {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_pojointentry(), 1,
              this_._impl_._pojointentry_cached_byte_size_);
    }
  }
   {
    // optional uint32 numJoints = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_numjoints());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void JointData_proto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<JointData_proto*>(&to_msg);
  auto& from = static_cast<const JointData_proto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:JointData_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_pojointentry()->MergeFrom(from._internal_pojointentry());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _this->_impl_.numjoints_ = from._impl_.numjoints_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void JointData_proto::CopyFrom(const JointData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:JointData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JointData_proto::InternalSwap(JointData_proto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pojointentry_.InternalSwap(&other->_impl_.pojointentry_);
  swap(_impl_.numjoints_, other->_impl_.numjoints_);
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
