// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: JointData.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef JointData_2eproto_2epb_2eh
#define JointData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_JointData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_JointData_2eproto {
  static const ::uint32_t offsets[];
};
class JointData_proto;
struct JointData_protoDefaultTypeInternal;
extern JointData_protoDefaultTypeInternal _JointData_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<16> JointData_proto_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class JointData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:JointData_proto) */ {
 public:
  inline JointData_proto() : JointData_proto(nullptr) {}
  ~JointData_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(JointData_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(JointData_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR JointData_proto(::google::protobuf::internal::ConstantInitialized);

  inline JointData_proto(const JointData_proto& from) : JointData_proto(nullptr, from) {}
  inline JointData_proto(JointData_proto&& from) noexcept
      : JointData_proto(nullptr, ::std::move(from)) {}
  inline JointData_proto& operator=(const JointData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline JointData_proto& operator=(JointData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const JointData_proto& default_instance() {
    return *reinterpret_cast<const JointData_proto*>(
        &_JointData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(JointData_proto& a, JointData_proto& b) { a.Swap(&b); }
  inline void Swap(JointData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JointData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JointData_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<JointData_proto>(arena);
  }
  void CopyFrom(const JointData_proto& from);
  void MergeFrom(const JointData_proto& from) { JointData_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(JointData_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "JointData_proto"; }

 protected:
  explicit JointData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  JointData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const JointData_proto& from);
  JointData_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, JointData_proto&& from) noexcept
      : JointData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPoJointEntryFieldNumber = 2,
    kNumBonesFieldNumber = 1,
  };
  // repeated uint32 poJointEntry = 2;
  int pojointentry_size() const;
  private:
  int _internal_pojointentry_size() const;

  public:
  void clear_pojointentry() ;
  ::uint32_t pojointentry(int index) const;
  void set_pojointentry(int index, ::uint32_t value);
  void add_pojointentry(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& pojointentry() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_pojointentry();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_pojointentry() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_pojointentry();

  public:
  // optional uint32 numBones = 1;
  bool has_numbones() const;
  void clear_numbones() ;
  ::uint32_t numbones() const;
  void set_numbones(::uint32_t value);

  private:
  ::uint32_t _internal_numbones() const;
  void _internal_set_numbones(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:JointData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const JointData_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint32_t> pojointentry_;
    ::google::protobuf::internal::CachedSize _pojointentry_cached_byte_size_;
    ::uint32_t numbones_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_JointData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<16> JointData_proto_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// JointData_proto

// optional uint32 numBones = 1;
inline bool JointData_proto::has_numbones() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void JointData_proto::clear_numbones() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numbones_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::uint32_t JointData_proto::numbones() const {
  // @@protoc_insertion_point(field_get:JointData_proto.numBones)
  return _internal_numbones();
}
inline void JointData_proto::set_numbones(::uint32_t value) {
  _internal_set_numbones(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:JointData_proto.numBones)
}
inline ::uint32_t JointData_proto::_internal_numbones() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numbones_;
}
inline void JointData_proto::_internal_set_numbones(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numbones_ = value;
}

// repeated uint32 poJointEntry = 2;
inline int JointData_proto::_internal_pojointentry_size() const {
  return _internal_pojointentry().size();
}
inline int JointData_proto::pojointentry_size() const {
  return _internal_pojointentry_size();
}
inline void JointData_proto::clear_pojointentry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pojointentry_.Clear();
}
inline ::uint32_t JointData_proto::pojointentry(int index) const {
  // @@protoc_insertion_point(field_get:JointData_proto.poJointEntry)
  return _internal_pojointentry().Get(index);
}
inline void JointData_proto::set_pojointentry(int index, ::uint32_t value) {
  _internal_mutable_pojointentry()->Set(index, value);
  // @@protoc_insertion_point(field_set:JointData_proto.poJointEntry)
}
inline void JointData_proto::add_pojointentry(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pojointentry()->Add(value);
  // @@protoc_insertion_point(field_add:JointData_proto.poJointEntry)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& JointData_proto::pojointentry() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:JointData_proto.poJointEntry)
  return _internal_pojointentry();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL JointData_proto::mutable_pojointentry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:JointData_proto.poJointEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pojointentry();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
JointData_proto::_internal_pojointentry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pojointentry_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
JointData_proto::_internal_mutable_pojointentry() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pojointentry_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // JointData_2eproto_2epb_2eh
