// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SkelData.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef SkelData_2eproto_2epb_2eh
#define SkelData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "SkelEntry.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_SkelData_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_SkelData_2eproto {
  static const ::uint32_t offsets[];
};
class SkelData_proto;
struct SkelData_protoDefaultTypeInternal;
extern SkelData_protoDefaultTypeInternal _SkelData_proto_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<15> SkelData_proto_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class SkelData_proto final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:SkelData_proto) */ {
 public:
  inline SkelData_proto() : SkelData_proto(nullptr) {}
  ~SkelData_proto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SkelData_proto* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SkelData_proto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SkelData_proto(::google::protobuf::internal::ConstantInitialized);

  inline SkelData_proto(const SkelData_proto& from) : SkelData_proto(nullptr, from) {}
  inline SkelData_proto(SkelData_proto&& from) noexcept
      : SkelData_proto(nullptr, ::std::move(from)) {}
  inline SkelData_proto& operator=(const SkelData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline SkelData_proto& operator=(SkelData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const SkelData_proto& default_instance() {
    return *reinterpret_cast<const SkelData_proto*>(
        &_SkelData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SkelData_proto& a, SkelData_proto& b) { a.Swap(&b); }
  inline void Swap(SkelData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SkelData_proto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SkelData_proto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<SkelData_proto>(arena);
  }
  void CopyFrom(const SkelData_proto& from);
  void MergeFrom(const SkelData_proto& from) { SkelData_proto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SkelData_proto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "SkelData_proto"; }

 protected:
  explicit SkelData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SkelData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SkelData_proto& from);
  SkelData_proto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SkelData_proto&& from) noexcept
      : SkelData_proto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPoSkelEntryFieldNumber = 3,
    kPVersionFieldNumber = 1,
    kNumNodesFieldNumber = 2,
  };
  // repeated .SkelEntry_proto poSkelEntry = 3;
  int poskelentry_size() const;
  private:
  int _internal_poskelentry_size() const;

  public:
  void clear_poskelentry() ;
  ::SkelEntry_proto* PROTOBUF_NONNULL mutable_poskelentry(int index);
  ::google::protobuf::RepeatedPtrField<::SkelEntry_proto>* PROTOBUF_NONNULL mutable_poskelentry();

  private:
  const ::google::protobuf::RepeatedPtrField<::SkelEntry_proto>& _internal_poskelentry() const;
  ::google::protobuf::RepeatedPtrField<::SkelEntry_proto>* PROTOBUF_NONNULL _internal_mutable_poskelentry();
  public:
  const ::SkelEntry_proto& poskelentry(int index) const;
  ::SkelEntry_proto* PROTOBUF_NONNULL add_poskelentry();
  const ::google::protobuf::RepeatedPtrField<::SkelEntry_proto>& poskelentry() const;
  // optional bytes pVersion = 1;
  bool has_pversion() const;
  void clear_pversion() ;
  const ::std::string& pversion() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_pversion(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_pversion();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_pversion();
  void set_allocated_pversion(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_pversion() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_pversion(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_pversion();

  public:
  // optional uint32 numNodes = 2;
  bool has_numnodes() const;
  void clear_numnodes() ;
  ::uint32_t numnodes() const;
  void set_numnodes(::uint32_t value);

  private:
  ::uint32_t _internal_numnodes() const;
  void _internal_set_numnodes(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:SkelData_proto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SkelData_proto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::SkelEntry_proto > poskelentry_;
    ::google::protobuf::internal::ArenaStringPtr pversion_;
    ::uint32_t numnodes_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_SkelData_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<15> SkelData_proto_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SkelData_proto

// optional bytes pVersion = 1;
inline bool SkelData_proto::has_pversion() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  return value;
}
inline void SkelData_proto::clear_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pversion_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& SkelData_proto::pversion() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:SkelData_proto.pVersion)
  return _internal_pversion();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SkelData_proto::set_pversion(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pversion_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:SkelData_proto.pVersion)
}
inline ::std::string* PROTOBUF_NONNULL SkelData_proto::mutable_pversion()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_pversion();
  // @@protoc_insertion_point(field_mutable:SkelData_proto.pVersion)
  return _s;
}
inline const ::std::string& SkelData_proto::_internal_pversion() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pversion_.Get();
}
inline void SkelData_proto::_internal_set_pversion(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.pversion_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SkelData_proto::_internal_mutable_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.pversion_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SkelData_proto::release_pversion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:SkelData_proto.pVersion)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.pversion_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.pversion_.Set("", GetArena());
  }
  return released;
}
inline void SkelData_proto::set_allocated_pversion(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.pversion_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.pversion_.IsDefault()) {
    _impl_.pversion_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:SkelData_proto.pVersion)
}

// optional uint32 numNodes = 2;
inline bool SkelData_proto::has_numnodes() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002U) != 0;
  return value;
}
inline void SkelData_proto::clear_numnodes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numnodes_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint32_t SkelData_proto::numnodes() const {
  // @@protoc_insertion_point(field_get:SkelData_proto.numNodes)
  return _internal_numnodes();
}
inline void SkelData_proto::set_numnodes(::uint32_t value) {
  _internal_set_numnodes(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:SkelData_proto.numNodes)
}
inline ::uint32_t SkelData_proto::_internal_numnodes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.numnodes_;
}
inline void SkelData_proto::_internal_set_numnodes(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.numnodes_ = value;
}

// repeated .SkelEntry_proto poSkelEntry = 3;
inline int SkelData_proto::_internal_poskelentry_size() const {
  return _internal_poskelentry().size();
}
inline int SkelData_proto::poskelentry_size() const {
  return _internal_poskelentry_size();
}
inline ::SkelEntry_proto* PROTOBUF_NONNULL SkelData_proto::mutable_poskelentry(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:SkelData_proto.poSkelEntry)
  return _internal_mutable_poskelentry()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::SkelEntry_proto>* PROTOBUF_NONNULL SkelData_proto::mutable_poskelentry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:SkelData_proto.poSkelEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_poskelentry();
}
inline const ::SkelEntry_proto& SkelData_proto::poskelentry(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:SkelData_proto.poSkelEntry)
  return _internal_poskelentry().Get(index);
}
inline ::SkelEntry_proto* PROTOBUF_NONNULL SkelData_proto::add_poskelentry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::SkelEntry_proto* _add = _internal_mutable_poskelentry()->Add();
  // @@protoc_insertion_point(field_add:SkelData_proto.poSkelEntry)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::SkelEntry_proto>& SkelData_proto::poskelentry() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:SkelData_proto.poSkelEntry)
  return _internal_poskelentry();
}
inline const ::google::protobuf::RepeatedPtrField<::SkelEntry_proto>&
SkelData_proto::_internal_poskelentry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.poskelentry_;
}
inline ::google::protobuf::RepeatedPtrField<::SkelEntry_proto>* PROTOBUF_NONNULL
SkelData_proto::_internal_mutable_poskelentry() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.poskelentry_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // SkelData_2eproto_2epb_2eh
