// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SkelEntry.proto
// Protobuf C++ Version: 6.32.0-dev

#include "SkelEntry.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr SkelEntry_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pnodename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        nodeindex_{0},
        parentindex_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SkelEntry_proto::SkelEntry_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(SkelEntry_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SkelEntry_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SkelEntry_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SkelEntry_protoDefaultTypeInternal() {}
  union {
    SkelEntry_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SkelEntry_protoDefaultTypeInternal _SkelEntry_proto_default_instance_;
// ===================================================================

class SkelEntry_proto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SkelEntry_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SkelEntry_proto, _impl_._has_bits_);
};

SkelEntry_proto::SkelEntry_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, SkelEntry_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SkelEntry_proto)
}
PROTOBUF_NDEBUG_INLINE SkelEntry_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::SkelEntry_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pnodename_(arena, from.pnodename_) {}

SkelEntry_proto::SkelEntry_proto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SkelEntry_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, SkelEntry_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SkelEntry_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, nodeindex_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, nodeindex_),
           offsetof(Impl_, parentindex_) -
               offsetof(Impl_, nodeindex_) +
               sizeof(Impl_::parentindex_));

  // @@protoc_insertion_point(copy_constructor:SkelEntry_proto)
}
PROTOBUF_NDEBUG_INLINE SkelEntry_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        pnodename_(arena) {}

inline void SkelEntry_proto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, nodeindex_),
           0,
           offsetof(Impl_, parentindex_) -
               offsetof(Impl_, nodeindex_) +
               sizeof(Impl_::parentindex_));
}
SkelEntry_proto::~SkelEntry_proto() {
  // @@protoc_insertion_point(destructor:SkelEntry_proto)
  SharedDtor(*this);
}
inline void SkelEntry_proto::SharedDtor(MessageLite& self) {
  SkelEntry_proto& this_ = static_cast<SkelEntry_proto&>(self);
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.pnodename_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SkelEntry_proto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SkelEntry_proto(arena);
}
constexpr auto SkelEntry_proto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SkelEntry_proto),
                                            alignof(SkelEntry_proto));
}
constexpr auto SkelEntry_proto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<16>{
      {
          &_SkelEntry_proto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SkelEntry_proto::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<SkelEntry_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SkelEntry_proto::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<SkelEntry_proto>(), &SkelEntry_proto::ByteSizeLong,
              &SkelEntry_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SkelEntry_proto, _impl_._cached_size_),
          true,
      },
      "SkelEntry_proto",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<16> SkelEntry_proto_class_data_ =
    SkelEntry_proto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SkelEntry_proto::GetClassData() const {
  return SkelEntry_proto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
SkelEntry_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SkelEntry_proto, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SkelEntry_proto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::SkelEntry_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional sint32 nodeIndex = 1;
    {::_pbi::TcParser::FastZ32S1,
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(SkelEntry_proto, _impl_.nodeindex_)}},
    // optional sint32 parentIndex = 2;
    {::_pbi::TcParser::FastZ32S1,
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(SkelEntry_proto, _impl_.parentindex_)}},
    // optional bytes pNodeName = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(SkelEntry_proto, _impl_.pnodename_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional sint32 nodeIndex = 1;
    {PROTOBUF_FIELD_OFFSET(SkelEntry_proto, _impl_.nodeindex_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kSInt32)},
    // optional sint32 parentIndex = 2;
    {PROTOBUF_FIELD_OFFSET(SkelEntry_proto, _impl_.parentindex_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kSInt32)},
    // optional bytes pNodeName = 3;
    {PROTOBUF_FIELD_OFFSET(SkelEntry_proto, _impl_.pnodename_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SkelEntry_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:SkelEntry_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.pnodename_.ClearNonDefaultToEmpty();
  }
  if ((cached_has_bits & 0x00000006U) != 0) {
    ::memset(&_impl_.nodeindex_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.parentindex_) -
        reinterpret_cast<char*>(&_impl_.nodeindex_)) + sizeof(_impl_.parentindex_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SkelEntry_proto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SkelEntry_proto& this_ = static_cast<const SkelEntry_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SkelEntry_proto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SkelEntry_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:SkelEntry_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional sint32 nodeIndex = 1;
  if ((cached_has_bits & 0x00000002U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
        1, this_._internal_nodeindex(), target);
  }

  // optional sint32 parentIndex = 2;
  if ((cached_has_bits & 0x00000004U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
        2, this_._internal_parentindex(), target);
  }

  // optional bytes pNodeName = 3;
  if ((cached_has_bits & 0x00000001U) != 0) {
    const ::std::string& _s = this_._internal_pnodename();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SkelEntry_proto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SkelEntry_proto::ByteSizeLong(const MessageLite& base) {
  const SkelEntry_proto& this_ = static_cast<const SkelEntry_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SkelEntry_proto::ByteSizeLong() const {
  const SkelEntry_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:SkelEntry_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    // optional bytes pNodeName = 3;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_pnodename());
    }
    // optional sint32 nodeIndex = 1;
    if ((cached_has_bits & 0x00000002U) != 0) {
      total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
          this_._internal_nodeindex());
    }
    // optional sint32 parentIndex = 2;
    if ((cached_has_bits & 0x00000004U) != 0) {
      total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
          this_._internal_parentindex());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void SkelEntry_proto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SkelEntry_proto*>(&to_msg);
  auto& from = static_cast<const SkelEntry_proto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SkelEntry_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _this->_internal_set_pnodename(from._internal_pnodename());
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _this->_impl_.nodeindex_ = from._impl_.nodeindex_;
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      _this->_impl_.parentindex_ = from._impl_.parentindex_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void SkelEntry_proto::CopyFrom(const SkelEntry_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SkelEntry_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SkelEntry_proto::InternalSwap(SkelEntry_proto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pnodename_, &other->_impl_.pnodename_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SkelEntry_proto, _impl_.parentindex_)
      + sizeof(SkelEntry_proto::_impl_.parentindex_)
      - PROTOBUF_FIELD_OFFSET(SkelEntry_proto, _impl_.nodeindex_)>(
          reinterpret_cast<char*>(&_impl_.nodeindex_),
          reinterpret_cast<char*>(&other->_impl_.nodeindex_));
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
