// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: SkelData.proto
// Protobuf C++ Version: 6.32.0-dev

#include "SkelData.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr SkelData_proto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        poskelentry_{},
        pversion_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        numnodes_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR SkelData_proto::SkelData_proto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(SkelData_proto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SkelData_protoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SkelData_protoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SkelData_protoDefaultTypeInternal() {}
  union {
    SkelData_proto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SkelData_protoDefaultTypeInternal _SkelData_proto_default_instance_;
// ===================================================================

class SkelData_proto::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SkelData_proto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SkelData_proto, _impl_._has_bits_);
};

void SkelData_proto::clear_poskelentry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.poskelentry_.Clear();
}
SkelData_proto::SkelData_proto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, SkelData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SkelData_proto)
}
PROTOBUF_NDEBUG_INLINE SkelData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::SkelData_proto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        poskelentry_{visibility, arena, from.poskelentry_},
        pversion_(arena, from.pversion_) {}

SkelData_proto::SkelData_proto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SkelData_proto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, SkelData_proto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SkelData_proto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.numnodes_ = from._impl_.numnodes_;

  // @@protoc_insertion_point(copy_constructor:SkelData_proto)
}
PROTOBUF_NDEBUG_INLINE SkelData_proto::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        poskelentry_{visibility, arena},
        pversion_(arena) {}

inline void SkelData_proto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.numnodes_ = {};
}
SkelData_proto::~SkelData_proto() {
  // @@protoc_insertion_point(destructor:SkelData_proto)
  SharedDtor(*this);
}
inline void SkelData_proto::SharedDtor(MessageLite& self) {
  SkelData_proto& this_ = static_cast<SkelData_proto&>(self);
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.pversion_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SkelData_proto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SkelData_proto(arena);
}
constexpr auto SkelData_proto::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SkelData_proto, _impl_.poskelentry_) +
          decltype(SkelData_proto::_impl_.poskelentry_)::
              InternalGetArenaOffset(
                  ::google::protobuf::MessageLite::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(SkelData_proto), alignof(SkelData_proto), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SkelData_proto::PlacementNew_,
                                 sizeof(SkelData_proto),
                                 alignof(SkelData_proto));
  }
}
constexpr auto SkelData_proto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataLite<15>{
      {
          &_SkelData_proto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SkelData_proto::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<SkelData_proto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SkelData_proto::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<SkelData_proto>(), &SkelData_proto::ByteSizeLong,
              &SkelData_proto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SkelData_proto, _impl_._cached_size_),
          true,
      },
      "SkelData_proto",
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite<15> SkelData_proto_class_data_ =
    SkelData_proto::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SkelData_proto::GetClassData() const {
  return SkelData_proto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2>
SkelData_proto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SkelData_proto, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SkelData_proto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallbackLite,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::SkelData_proto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional bytes pVersion = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SkelData_proto, _impl_.pversion_)}},
    // optional uint32 numNodes = 2;
    {::_pbi::TcParser::FastV32S1,
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(SkelData_proto, _impl_.numnodes_)}},
    // repeated .SkelEntry_proto poSkelEntry = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(SkelData_proto, _impl_.poskelentry_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bytes pVersion = 1;
    {PROTOBUF_FIELD_OFFSET(SkelData_proto, _impl_.pversion_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional uint32 numNodes = 2;
    {PROTOBUF_FIELD_OFFSET(SkelData_proto, _impl_.numnodes_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // repeated .SkelEntry_proto poSkelEntry = 3;
    {PROTOBUF_FIELD_OFFSET(SkelData_proto, _impl_.poskelentry_), -1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::SkelEntry_proto>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void SkelData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:SkelData_proto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.poskelentry_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    _impl_.pversion_.ClearNonDefaultToEmpty();
  }
  _impl_.numnodes_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SkelData_proto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SkelData_proto& this_ = static_cast<const SkelData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SkelData_proto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SkelData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:SkelData_proto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional bytes pVersion = 1;
  if ((cached_has_bits & 0x00000001U) != 0) {
    const ::std::string& _s = this_._internal_pversion();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // optional uint32 numNodes = 2;
  if ((cached_has_bits & 0x00000002U) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_numnodes(), target);
  }

  // repeated .SkelEntry_proto poSkelEntry = 3;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_poskelentry_size());
       i < n; i++) {
    const auto& repfield = this_._internal_poskelentry().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            3, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SkelData_proto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SkelData_proto::ByteSizeLong(const MessageLite& base) {
  const SkelData_proto& this_ = static_cast<const SkelData_proto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SkelData_proto::ByteSizeLong() const {
  const SkelData_proto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:SkelData_proto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .SkelEntry_proto poSkelEntry = 3;
    {
      total_size += 1UL * this_._internal_poskelentry_size();
      for (const auto& msg : this_._internal_poskelentry()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    // optional bytes pVersion = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_pversion());
    }
    // optional uint32 numNodes = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_numnodes());
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void SkelData_proto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SkelData_proto*>(&to_msg);
  auto& from = static_cast<const SkelData_proto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SkelData_proto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_poskelentry()->MergeFrom(
      from._internal_poskelentry());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      _this->_internal_set_pversion(from._internal_pversion());
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      _this->_impl_.numnodes_ = from._impl_.numnodes_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(from._internal_metadata_);
}

void SkelData_proto::CopyFrom(const SkelData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SkelData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SkelData_proto::InternalSwap(SkelData_proto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.poskelentry_.InternalSwap(&other->_impl_.poskelentry_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pversion_, &other->_impl_.pversion_, arena);
  swap(_impl_.numnodes_, other->_impl_.numnodes_);
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
